### ISSUE TITLE
Confidence score interpretation

### ISSUE THREAD

**Issue by omansn** [YeoLab/sailor#5]
Hello Yeo Lab, 
Sailor seems really useful and well written. Thanks for taking the effort to pack it into a container and distribute it in an easy to deploy way. I am hoping to use Sailor for some of my work, but I have a few questions about its execution and interpretation. Thank you for taking the time to answer these.

1. Is there a paper or somewhere I can read about the underlying math? I see that the eLife paper has a 'request detailed protocol' link for the Sailor. is this available? If so, maybe my questions 2 will be answered there.

2.  I'm a little confused about the confidence score. Based on your code, the confidence score given in the output bed and VCF files is the inverse of the incomplete beta function with a=depth(G) b=depth(A) and x=cov_margin. You define cov_margin as the _minimum_ allowable edit fraction but the scipy betainc() function's variable x is the _maximum_ allowable value. What am I missing here? 

3. Related to question 2. Do you have suggestions for how to interpret the confidence score? What is the minimum confidence score you have found to be a true edit site?

4. When I ran the example dataset with the singularity container, there were no 'combined' files. Do I just run the combine_and_reformat.py script on my output? For unstranded libraries, do you have a recommendation of how to combine the confidence calls for fwd and rev calls?

I just want to thank you again for taking the time to answer these. I realize there are a lot of questions here for code you probably haven't looked at for a while.

**Comment by byee4** [comment]
Hi, yes I'll need to take a look at this script in particular, but I believe it was just taken from the methods from this paper: [The dsRBP and inactive editor, ADR-1, utilizes dsRNA binding to regulate A-to-I RNA editing across the C. elegans transcriptome](https://pubmed.ncbi.nlm.nih.gov/24508457/).
For determining confidence score, we used a control that allowed us to see at which confidence minimized the number of false positives, similar to the original paper. 
I'm not sure if SAILOR fully supports unstranded reads (I'll have to check) since one of the first steps is to split by strand so we know whether or not to call an A>I or T>C. There may be ways to guess the strand based on some existing annotation, but that wasn't implemented in this pipeline.
